### ISSUE TITLE
The Kubernetes nginx CSI example test is failed

### ISSUE THREAD

**Issue by kevinjantw** [opensds/nbp#248] opened 2019-07-23 09:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
  Maybe a bug or not

**What happened**:
   I follow the two guides to install Kubernetes & OpenSDS successfully and test them.
   Everything is OK, but nginx CSI example test is failed.
   https://github.com/opensds/opensds/wiki/OpenSDS-Integration-with-Kubernetes-CSI
   https://github.com/opensds/opensds/wiki/OpenSDS-Cluster-Installation-through-Ansible

**What you expected to happen**:
  The `kubectl create -f nginx.yaml` was passed,
  but the `kubectl get pod nginx` got a nginx pod in Pending status.
  I expected the nginx was in Running status.

**How to reproduce it (as minimally and precisely as possible)**:
  (1) Install Kubernetes & OpenSDS on one Virtualbox VM
  (2) The used csi-configmap-opensdsplugin.yaml during OpenSDS deployment  

    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: csi-configmap-opensdsplugin
    data:
      opensdsendpoint: http://127.0.0.1:50040
      opensdsauthstrategy: noauth
      opensdsstoragetype: block
      osauthurl: http://127.0.0.1/identity
      osusername: admin
      ospassword: opensds@123
      ostenantname: admin
      osprojectname: admin
      osuserdomainid: default
      passwordencrypter: aes
      enableEncrypted: F
      osuserdomainid: default
 
 (3) After finishing OpenSDS deployment, run `kubectl get pod` to show
  the four pods: csi-attacher-opensdsplugin, csi-nodeplugin-opensdsplugin,  
  csi-provisioner-opensdsplugin and csi-snapshotter-opensdsplugin were Running normally.      

 (4) Run `kubectl create -f nginx.yaml` and `kubectl get pod nginx`

**Anything else we need to know?**:
  The `kubectl get pvc` showed csi-pvc-opensdsplugin was in Pending status and 
  `kubectl describe pvc csi-pvc-opensdsplugin` showed a failed message:
  "failed to provision volume with StorageClass "csi-sc-opensdsplugin": rpc error: code = 
  InvalidArgument desc = get profile abc failed"

  Detailed message snapshot:
  https://1drv.ms/u/s!AtJnzpDx-p62uDRM8QWCFBBL00-E

**Environment**:
- NBP version: latest version
- OS (e.g. from /etc/os-release): ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`): 4.15.0-45-generic
- Install tools: ansible
- Docker version: 18.06.1-ce
- Kubernetes version: v1.14.0

**Comment by wisererik** [comment] 2019-07-23 10:10
Hi Kevin, thanks for telling us the issue. From message you provided, maybe on problem is that csi plugin was installed correctly. I assume you have changed the `host_ip` (such as: 192.168.22.97) in installer configuration. please update configmap like the bellowing: 
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: csi-configmap-opensdsplugin
data:
  opensdsendpoint: http://192.168.22.97:50040 
  opensdsauthstrategy: keystone
  opensdsstoragetype: block
  osauthurl: http://192.168.22.97/identity
  osusername: admin
  ospassword: opensds@123
  ostenantname: admin
  osprojectname: admin
  osuserdomainid: default
  passwordencrypter: aes
  enableEncrypted: F
  osuserdomainid: default
```
Then re-install  csi plugin by using kubectl delete/create -f *

**Comment by kevinjantw** [comment] 2019-07-23 11:20
Thanks Erik,
But the HOST_IP has same IP configuration as configmap file.
The `export HOST_IP=127.0.0.1` was configed before running opensds-ansible playbook deployment.
After opensds deployment, the 127.0.0.1 was also applied to {your_real_host_ip} in opensds CLI tool configuration and all osdsctl command tests are OK.

**Comment by wisererik** [comment] 2019-07-23 11:34
OK, maybe I know the issue. As a container, CSI plugin cannot reach to opensds hotpot service if we use 127.0.0.1.  So we should change the HOST_IP.

**Comment by kevinjantw** [comment] 2019-07-24 09:32
The HOST_IP has been changed from 127.0.0.1 to 10.0.2.15, 
but the issue still exists. I highlight the installation and test details as follows. 


Kubernetes installation and test:
   
     ENABLE_DAEMON=true ALLOW_PRIVILEGED=true 
     FEATURE_GATES=VolumeSnapshotDataSource=true
     RUNTIME_CONFIG="storage.k8s.io/v1alpha1=true" LOG_LEVEL=5 hack/local-up-cluster.sh -O

     kubectl get nodes

NAME  |       STATUS |   ROLES  |   AGE |   VERSION
------------ | ------------- | ------------- | ------------- | -------------
127.0.0.1  |  Ready  |   none   | 51m   | v1.14.0

OpenSDS installation and osdsctl test:

    group_vars/common.yml
    host_ip: 10.0.2.15

    group_vars/sushi.yml:
    nbp_plugin_type: csi

    export HOST_IP=10.0.2.15

    osdsctl profile create '{"name": "default", "description": "default policy", "storageType": "block"}'
    osdsctl volume create 1 --name=test-001
    osdsctl volume list

Id |   Name |   Description  |  GroupId  |  Size  |  Status | ProfileId 
------------ | ------------- | ------------- | ------------- | ------------- |  ------------- |  ------------- 
13311bbe-a46c-4403-acfd-0589f449cd21 | test-001 |  |  | 1 |  available | d10ec339-3357-43ff-8626-4ccdb854af3d

OpenSDS CSI Plugin test:

`cat csi-configmap-opensdsplugin.yaml`

    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: csi-configmap-opensdsplugin
    data:
      opensdsendpoint: http://10.0.2.15:50040
      opensdsauthstrategy: keystone
      opensdsstoragetype: block
      osauthurl: http://10.0.2.15/identity
      osusername: admin
      ospassword: opensds@123
      ostenantname: admin
      osprojectname: admin
      osuserdomainid: default
      passwordencrypter: aes
      enableEncrypted: F
      osuserdomainid: default

`kubectl create -f nginx.yaml`
`kubectl get pods`

NAME |        READY |   STATUS |  RESTARTS |  AGE
------------ | ------------- | ------------- | ------------- | -------------
csi-attacher-opensdsplugin-0  |       3/3  |   Running |  0       |   34m
csi-nodeplugin-opensdsplugin-gd9j2 |  2/2   |  Running |  0    |      34m
csi-provisioner-opensdsplugin-0   |   2/2   |  Running |  0      |    34m
csi-snapshotter-opensdsplugin-0   |   2/2  |   Running |  0    |      34m
nginx        |                        0/1  |   Pending  | 0    |      27m

`kubectl get pvc`

NAME |    STATUS|     VOLUME|    CAPACITY|    ACCESS MODES |   STORAGECLASS |    AGE
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
csi-pvc-opensdsplugin  |  Pending | | | |    csi-sc-opensdsplugin  |  30m

`kubectl describe pvc csi-pvc-opensdsplugin`

Name:          csi-pvc-opensdsplugin
Namespace:     default
StorageClass:  csi-sc-opensdsplugin
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: csi-opensdsplugin
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:

Type|       Reason|                Age|                    From|  Message
 ------------ | ------------- | ------------- | ------------- | -------------
  Normal |    ExternalProvisioning | 4m46s (x121 over 34m) | persistentvolume-controller |                                                            waiting for a volume to be created, either by external provisioner "csi-opensdsplugin" or manually created by system administrator
  Normal |    Provisioning |         73s (x15 over 34m)  |   csi-opensdsplugin_csi-provisioner-opensdsplugin-0_93c03670-ade6-11e9-a4aa-0242ac110003 | External provisioner is provisioning volume for claim "default/csi-pvc-opensdsplugin"
  Warning |   ProvisioningFailed |   73s (x15 over 34m)   |  csi-opensdsplugin_csi-provisioner-opensdsplugin-0_93c03670-ade6-11e9-a4aa-0242ac110003 | failed to provision volume with StorageClass "csi-sc-opensdsplugin": rpc error: code = InvalidArgument desc = get profile abc failed

**Comment by wisererik** [comment] 2019-07-24 10:38
Thanks Kevin, it's very detailed. Profile need to be updated in nginx.yml, I'm sorry the wiki didn't mention it.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-opensdsplugin
provisioner: csi-opensdsplugin
parameters:
  attachMode: rw
  profile: d10ec339-3357-43ff-8626-4ccdb854af3d
```

**Comment by wisererik** [comment] 2019-07-24 10:52
BTW, I updated the CSI WIKI: 
https://github.com/opensds/opensds/wiki/OpenSDS-Integration-with-Kubernetes-CSI

Some of us are working on container storage, you can join opensds.slack.com to get quick feedback. :)

**Comment by kevinjantw** [comment] 2019-07-25 11:09
Thank for your invitation, I have joined your channels.
The updated profile has released the pended persistent volume claim, but the nginx pod still stuck at a ContainerCreating status.

`kubectl get nodes`

NAME |       STATUS|   ROLES |   AGE|   VERSION
--- |--- |--- |--- |---
127.0.0.1|   Ready |   none|   29h |  v1.14.0


`kubectl create -f nginx.yaml`
`kubectl get pvc`

NAME |   STATUS|   VOLUME|   CAPACITY|   ACCESS MODES|   STORAGECLASS|   AGE
--- |--- |--- |--- |--- |--- |--- 
csi-pvc-opensdsplugin|   Bound|    pvc-5c00e92f-addb-11e9-aae2-0800275197c7|   1Gi|    RWX|    csi-sc-opensdsplugin|   21s

`kubectl get pod`

NAME |                                 READY |   STATUS  |             RESTARTS |   AGE
--- |--- |--- |--- |---
csi-attacher-opensdsplugin-0|         3/3|     Running|             1|          8m51s
csi-nodeplugin-opensdsplugin-n7nlp|   2/2|     Running|         0|          8m50s
csi-provisioner-opensdsplugin-0|      2/2|     Running|             0|          8m50s
csi-snapshotter-opensdsplugin-0|      2/2|     Running|             0|          8m50s
nginx|                                0/1|     ContainerCreating|   0|          31s|
 
`kubectl describe pod nginx`

        Name: nginx
        Namespace: default
        Priority: 0
        PriorityClassName: <none>
        Node: 127.0.0.1/127.0.0.1
        Start Time: Wed, 24 Jul 2019 14:22:11 +0800
        Labels: <none>
        Annotations: <none>
        Status: Pending
        IP:                 
        Containers:
          nginx:
            Container ID:   
            Image: nginx
            Image ID:       
            Port: 80/TCP
            Host Port: 0/TCP
            State: Waiting
              Reason: ContainerCreating
            Ready: False
            Restart Count: 0
            Environment: <none>
            Mounts:
              /var/lib/www/html from csi-data-opensdsplugin (rw)
              /var/run/secrets/kubernetes.io/serviceaccount from default-token-z7vs2 (ro)
        Conditions:
          Type Status
          Initialized True 
          Ready False 
          ContainersReady False 
          PodScheduled True 
        Volumes:
          csi-data-opensdsplugin:
            Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
            ClaimName: csi-pvc-opensdsplugin
            ReadOnly: false
          default-token-z7vs2:
            Type: Secret (a volume populated by a Secret)
            SecretName: default-token-z7vs2
            Optional: false
        QoS Class: BestEffort
        Node-Selectors: <none>
        Tolerations: node.kubernetes.io/not-ready:NoExecute for 300s
                     node.kubernetes.io/unreachable:NoExecute for 300s
        Events:

 Type |    Reason   |               Age |               From   |                  Message
--- |--- |--- |--- |---
  Warning|  FailedScheduling|        46s (x3 over 48s)|  default-scheduler|        pod has unbound immediate PersistentVolumeClaims|
  Normal |  Scheduled |              43s  |              default-scheduler|        Successfully assigned default/nginx to 127.0.0.1
  Normal |  SuccessfulAttachVolume|  43s |               attachdetach-controller|  AttachVolume.Attach succeeded for volume "pvc-5c00e92f-addb-11e9-aae2-0800275197c7"
  Warning | FailedMount  |           13s (x6 over 34s) | kubelet, 127.0.0.1|       MountVolume.MountDevice failed for volume "pvc-5c00e92f-addb-11e9-aae2-0800275197c7" : rpc error: code = FailedPrecondition desc = failed to find device: Please stop the iscsi process outside the container first: exit status 1

**Comment by wisererik** [comment] 2019-07-25 11:52
Can you please check if the `/sbin/iscsid` exists? Generally if it doesn't exist you can install `open-iscsi` manually.

**Comment by kevinjantw** [comment] 2019-07-26 02:11
Erik, 
The /sbin/iscsid was already installed, I resolved the issue by killing the iscsid processes.

**Comment by wisererik** [comment] 2019-07-26 10:14
My system woks fine, but I will check the mount function to find the reason, thanks Kevin.

**Comment by himanshuvar** [comment] 2019-08-31 02:01
@wisererik @kevinjantw If the example test is working fine, Can we close this issue?

**Comment by jaemin-joo** [comment] 2019-09-06 03:00
> The `/sbin/iscsid` was already installed, I resolved the issue by killing iscsid processes.
> Now nginx pod can execute normally into Running status.

Hello~ I got similar issue in my system. Can you know me how to resolve the issue? Did you kill process of iscsi?

**Comment by wisererik** [comment] 2019-09-06 04:12
@himanshuvar please have a look at it again, thanks~

**Comment by jaemin-joo** [comment] 2019-09-06 11:56
I changed configMap from domain name to Cluster-IP in kubernetes service.
it starts to work. but I failed to apply "nginx.yaml" 
please check syslog. let me know if you need to more information.

\# This YAML file contains configmap objects,
\# which are necessary to run csi opensds plugin.

kind: ConfigMap
apiVersion: v1
metadata:
name: csi-configmap-opensdsplugin
data:
opensdsendpoint: http://apiserver.opensds.svc.cluster.local:50040
opensdsauthstrategy: keystone
opensdsstoragetype: block
osauthurl: http://authchecker.opensds.svc.cluster.local/identity
osusername: admin
ospassword: opensds@123
ostenantname: admin
osprojectname: admin
osuserdomainid: default
passwordencrypter: aes
enableEncrypted: F
osuserdomainid: default

root@opensds:~/nbp/csi/server/deploy/kubernetes# kubectl get all
NAME                                     READY   STATUS    RESTARTS   AGE
pod/csi-attacher-opensdsplugin-0         3/3     Running   0          6m22s
pod/csi-nodeplugin-opensdsplugin-9sztb   2/2     Running   0          6m21s
pod/csi-provisioner-opensdsplugin-0      2/2     Running   0          6m20s
pod/csi-snapshotter-opensdsplugin-0      2/2     Running   0          6m20s

root@opensds:~# cat nginx.yaml 
# This YAML file contains nginx & csi opensds driver objects,
# which are necessary to run nginx with csi opensds driver.

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-sc-opensdsplugin
provisioner: csi-opensdsplugin
parameters:
  attachMode: rw
  profile: 477132ef-d9b6-4a2f-a0a0-a0468be08d90
allowedTopologies:
- matchLabelExpressions:
  - key: topology.csi-opensdsplugin/zone
    values:
    - default'


/var/log/syslog

Sep  6 20:48:39 localhost kubelet[1109]: E0906 20:48:39.722420    1109 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/csi-opensdsplugin^47d2555a-ba5c-4f47-a22c-d8f0d2be0189\"" failed. No retries permitted until 2019-09-06 20:49:43.722403621 +0900 KST m=+24114.113890425 (durationBeforeRetry 1m4s). Error: "MountVolume.MountDevice failed for volume \"pvc-2398729a-6daf-4835-a215-f69d18e5c37f\" (UniqueName: \"kubernetes.io/csi/csi-opensdsplugin^47d2555a-ba5c-4f47-a22c-d8f0d2be0189\") pod \"nginx\" (UID: \"41d344d7-ab0b-4359-b983-cb1c690575b1\") : rpc error: code = FailedPrecondition desc = failed to find device: exit status 21"
Sep  6 20:48:52 localhost kubelet[1109]: I0906 20:48:52.848147    1109 reconciler.go:177] operationExecutor.UnmountVolume started for volume "default-token-t4wqc" (UniqueName: "kubernetes.io/secret/41d344d7-ab0b-4359-b983-cb1c690575b1-default-token-t4wqc") pod "41d344d7-ab0b-4359-b983-cb1c690575b1" (UID: "41d344d7-ab0b-4359-b983-cb1c690575b1")
Sep  6 20:48:52 localhost kubelet[1109]: I0906 20:48:52.862561    1109 operation_generator.go:860] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/41d344d7-ab0b-4359-b983-cb1c690575b1-default-token-t4wqc" (OuterVolumeSpecName: "default-token-t4wqc") pod "41d344d7-ab0b-4359-b983-cb1c690575b1" (UID: "41d344d7-ab0b-4359-b983-cb1c690575b1"). InnerVolumeSpecName "default-token-t4wqc". PluginName "kubernetes.io/secret", VolumeGidValue ""
Sep  6 20:48:52 localhost kubelet[1109]: I0906 20:48:52.948748    1109 reconciler.go:297] Volume detached for volume "default-token-t4wqc" (UniqueName: "kubernetes.io/secret/41d344d7-ab0b-4359-b983-cb1c690575b1-default-token-t4wqc") on node "opensds" DevicePath ""
Sep  6 20:49:02 localhost kubelet[1109]: I0906 20:49:02.873967    1109 reconciler.go:297] Volume detached for volume "pvc-2398729a-6daf-4835-a215-f69d18e5c37f" (UniqueName: "kubernetes.io/csi/csi-opensdsplugin^47d2555a-ba5c-4f47-a22c-d8f0d2be0189") on node "opensds" DevicePath ""

**Comment by himanshuvar** [comment] 2019-09-09 06:35
@jaemin-joo Could you please try Kubernetes cluster v1.14.0
Here is the link for OpenSDS integration with Kubernetes CSI. 
https://github.com/opensds/opensds/wiki/OpenSDS-Integration-with-Kubernetes-CSI
Pods are deployed successfully for me, except the example test issue reported by @kevinjantw . The application is stuck in ContainerCreating state

**Comment by jaemin-joo** [comment] 2019-09-09 11:33
@himanshuvar OK. I will try to test in v1.14.0.

Can I use dns in the configMap file like below? (e.g. http://apiserver.opensds.svc.cluster.local:50040)
When I try to use dns, csi-nodeplugin pod has failed. and when I use Cluster-IP of apiserver & authchecker, it works. 
Another pod(csi-attacher, csi-provisioner, csi-snapshotter) works whatever DNS and ClusterIP.

kind: ConfigMap
apiVersion: v1
metadata:
name: csi-configmap-opensdsplugin
data:
opensdsendpoint: http://apiserver.opensds.svc.cluster.local:50040
opensdsauthstrategy: keystone
opensdsstoragetype: block
osauthurl: http://authchecker.opensds.svc.cluster.local/identity
osusername: admin
ospassword: opensds@123
ostenantname: admin
osprojectname: admin
osuserdomainid: default
passwordencrypter: aes
enableEncrypted: F
osuserdomainid: default

**Comment by jaemin-joo** [comment] 2019-09-16 10:47
When I checked configuration file. I found the issue is related to IP. It works when I change `tgtBindIp` to host-IP  in `/etc/opensds/driver/lvm.yaml`

```
root@opensds-srv01:~# vi /etc/opensds/driver/lvm.yaml

tgtBindIp: 192.168.0.86 # This section!!
tgtConfDir: /etc/tgt/conf.d
pool:
  lb001:
    storageType: block
    availabilityZone: default
    extras:
      dataStorage:
        provisioningPolicy: Thin
        isSpaceEfficient: false
      ioConnectivity:
        accessProtocol: iscsi
        maxIOPS: 7000000
        maxBWS: 600
      advanced:
        diskType: SSD
        latency: 5ms
```

But dock is possible to move to other node if node is down. so It doesn't solve the issue.

**Closed** 2019-09-23 04:34 UTC
Labels: bug

**Comment by jaemin-joo** [comment] 2019-09-25 09:03
Can I ask you why node iscsid process is checked more?
In my case, I attached iscsi volume to node which dock and csiplugin is placed. 
so I can find some of errors to use nginx example for CSI.
````
root@opensds-srv01:~# kubectl logs -f pod/csi-nodeplugin-opensdsplugin-4dk5j -c opensds

I0925 17:25:35.358873       1 logs.go:40] 2019/09/25 17:25:35 helper.go:236: connmap info:  map[discard:false targetDiscovered:true targetIQN:[iqn.2017-10.io.opensds:cdda11b8-e04f-4f49-8c16-0f88d761859e] targetLun:1 targetPortal:[192.168.0.11:3260]]
I0925 17:25:35.358885       1 logs.go:40] 2019/09/25 17:25:35 helper.go:237: conn info is:  &{    true [iqn.2017-10.io.opensds:cdda11b8-e04f-4f49-8c16-0f88d761859e] [192.168.0.11:3260]  1 false}
I0925 17:25:35.358892       1 logs.go:40] 2019/09/25 17:25:35 common.go:27: Command: /bin/bash -c pgrep -f /sbin/iscsid:
I0925 17:25:35.360933       1 logs.go:40] 2019/09/25 17:25:35 common.go:27: Command: /bin/bash -c /sbin/iscsid:
E0925 17:25:35.362435       1 volume.go:569] failed to find device: Please stop the iscsi process outside the container first: exit status 1
I0925 17:25:35.362444       1 node.go:79] end to node stage volume
````
